### ISSUE TITLE
Cannot Add repo

### ISSUE THREAD

**Issue by Sarabjyot** [Aparoksha18/Aparoksha-Data#3]
Unable to push or add repo

**Comment by sashank27** [comment]
Please add the data you want to insert in the issue
paste the part of json you want to add, and add the image

**Comment by Sarabjyot** [comment]
![mrgoogler](https://user-images.githubusercontent.com/37347287/37368349-ffe049a8-272b-11e8-8d81-c74fd24424ef.png)
Add this image

**Comment by Sarabjyot** [comment]
{
		"id": 133,
		"name": "Mr. Googler",
		"description": "The phrase ‘Google it’ has become synonymous with searching for all possible answers on the web with just a click. Almost everyone knows how to google but do you have what it takes to be 'Mr. Googler' ? If Yes ! then this is just the right place for you. All you have to do is Google answers and win exciting prizes !!",
		"location": "Computer Centre 3",
		"timestamp": 1521392400,
		"imageUrl": "",
		"duration": 60,
		"facebookEventLink": "https://www.facebook.com/events/201426857281973/?notif_t=plan_edited&notif_id=1520920328780812",
		"additionalInfo": [],
		"categories": [
			"miscellaneous"
		],
		"organizers": [{
			"Organizer1": "Vijay Giri",
			"phoneNumber1": 9453834673,
			"Organizer2": "Sarbjyot Singh",
			"phoneNumber2": 7571840301

		}]
	},

The json part
